defmodule LearningAsh.Repo.Migrations.AddSaleResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sale, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :buyer_name, :text, null: false
      add :seller_name, :text, null: false
      add :product_name, :text, null: false
      add :quantity, :bigint, null: false
      add :unity_price, :float, null: false
      add :total_price, :float, null: false
      add :product_desc, :text, null: false

      add :sale_date, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:sale)
  end
end
